version: '3.8'
services:
  eureka-server:
    image: 'valzhanov/migration-assistance-reactive-server:v2'
    container_name: eureka-server
    ports:
      - "8083:8083"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8083/eureka

  eureka-gateway:
    image: 'valzhanov/migration-assistance-reactive-gateway:v2'
    container_name: eureka-gateway
    ports:
      - "8080:8080"
    depends_on:
      -  eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8083/eureka
    links:
      -  eureka-server

  eureka-user-service:
    image: 'valzhanov/migration-assistance-reactive-user-service:v2'
    container_name: eureka-user-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-gateway
      - db
    environment:
       EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://eureka-server:8083/eureka
       SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/obtaining_citizenship
       SPRING_FLYWAY_USERNAME: postgres
       SPRING_FLYWAY_PASSWORD: root
       SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/obtaining_citizenship
       SPRING_R2DBC_USERNAME: postgres
       SPRING_R2DBC_PASSWORD: root

    links:
      - eureka-server

  eureka-testing-service:
    image: 'valzhanov/migration-assistance-reactive-testing-service:v2'
    container_name: eureka-testing-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-gateway
      - mongodb
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://eureka-server:8083/eureka
      MONGO.MIGRATION: /MigrationTest.json
      SPRING.DATA.MONGODB.URI: mongodb://root1:root2@mongodb:27017/mongo?authSource=admin



    links:
      - eureka-server

  eureka-map-service:
    image: 'valzhanov/migration-assistance-reactive-map-service:v2'
    container_name: eureka-map-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-gateway
      - mongodb
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://eureka-server:8083/eureka
      MONGO.MIGRATION: /migration/MigrationMap.json
      SPRING.DATA.MONGODB.URI: mongodb://root1:root2@mongodb:27017/mongo?authSource=admin

    links:
      - eureka-server

  eureka-client:
    image: 'valzhanov/migration-assistance-cloud-reactive-client:v2'
    container_name: eureka-client
    ports:
      - "8081:8081"
    depends_on:
      - eureka-gateway
    restart: unless-stopped
    stdin_open: true

  db:
    image: 'postgres:13.7'
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: obtaining_citizenship
    ports:
      - "5432:5432"
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root1
      - MONGO_INITDB_ROOT_PASSWORD=root2
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8085:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root1
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root2
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  data: { }

networks:
  default:
      name: mongodb_network
